export const SECONDS_PER_MINUTE = 60;
export const SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE;
export const SECONDS_PER_DAY = 24 * SECONDS_PER_HOUR;

export const APP_UPDATE_CHECK_INTERVAL_SECONDS = 3 * SECONDS_PER_HOUR;
export const CLEAR_VRCX_CACHE_DEFAULT_FREQUENCY_SECONDS = 2 * SECONDS_PER_DAY;
export const CLEAR_VRCX_CACHE_DISABLED_RETRY_DELAY_SECONDS = SECONDS_PER_HOUR;
export const CLEAR_VRCX_CACHE_MIN_DEFER_SECONDS = SECONDS_PER_MINUTE;
export const CLEAR_VRCX_CACHE_CADENCE_SECONDS = SECONDS_PER_DAY;
export const UPDATE_READY_TOAST_DURATION_MS = 4000;
